# you can override this using by setting a system property, for example -Des.logger.level=DEBUG
es.logger.level: WARN
rootLogger: ${es.logger.level}, console
logger:
  # log action execution errors for easier debugging
  action.admin: WARN
  action.search: DEBUG
  # reduce the logging for aws, too much is logged under the default INFO
  com.amazonaws: WARN
  index.indexing.slowlog: TRACE, slowlog_index
  index.search.slowlog: TRACE, slowlog_search

appender:
  console:
    type: console
    layout:
      type: enhancedPattern
      conversionPattern: "type=elasticsearch;timestamp=%d{ISO8601};severity=%p;category=%c;message=%m%n%throwable{1}"

  slowlog_index:
    type: console
    layout:
      type: pattern
      conversionPattern: "type=elasticsearch_slowlog_index;timestamp=%d{ISO8601};severity=%p;category=%c;message=%m%n%throwable{1}"

  slowlog_search:
    type: console
    layout:
      type: pattern
      conversionPattern: "type=elasticsearch_slowlog_search;timestamp=%d{ISO8601};severity=%p;category=%c;message=%m%n%throwable{1}"
